### ISSUE TITLE
pretty `args` `pre-commit-config`

### ISSUE THREAD

**Issue by vtrokhymenko** [vtrokhymenko/dst#150]
like to
```
repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=119

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --per-file-ignores=*/__init__.py:F401
          - --ignore=E501,W503
          - --max-line-length=119
        additional_dependencies:
          - flake8-bugbear==21.11.29
          - flake8-builtins==1.5.3
          - pep8-naming==0.12.1
          - flake8-variables-names==0.0.4
          - flake8-commas==2.1.0
          - flake8-mock==0.3
          - flake8-printf-formatting==1.1.2
          - flake8-pytest-style==1.5.1
          - flake8-simplify==0.14.2

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
```
